const names1 = [
    'La Pepica',
    'La pascuala',
    'Don Francisco',
    'El cacahuet',
    'La papallona',
    'Terra',
    'Montaet',
    'Manolin',
    'Churro',
    'LHorta',
    'Mar',
    'Formatge',
    'Estiu',
    'A Fer La Ma',
    'Llombai',
    'Poble',
    'Porta',
    'Pais Valencia',
    'Virgen',
    'Megumi',
    'Caseta',
    'Chiringuito',
    'Bar',
    'Asador',
    'Taberna',
    'Raco'
]

const names2 = [
    'Dorada',
    'Dur',
    'Espojos',
    'Fresquet',
    'Socarrat',
    'Botifarra',
    'Tomaqueta',
    'del Cultiu',
    'del arros',
    'de Paquita',
    'del Raco',
    'del Conill',
    'Vallbona',
    'Tallada',
    'Amoros',
    'de Juan',
    'y qués',
    'caloret',
    'Albufera',
    'Marilén',
    'Fusió'
]

const locations = [
    'Asakusa',
    'Ginza',
    'Ueno',
    'Tabata',
    'Nippori',
    'Nishi-Nippori',
    'Takadanobaba',
    'Ebisu',
    'Minatomirai',
    'Mizonokuchi',
    'Futako-Tamagawa',
    'Noborito',
    'Nerima',
    'Saitama',
    'Shinagawa',
    'Meguro',
    'Daikanyama',
    'Shibuya',
    'Shinjuku',
    'Shin-Okubo',
    'Setagaya',
    'Nakano',
    'Honanncho',
    'Azabujan',
    'Roppongi',
    'Chiyoda'
]

export { names1, names2, locations }